# Generated by Django 5.1.3 on 2024-11-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='ascendant',
            field=models.IntegerField(blank=True, null=True, verbose_name='асцендент'),
        ),
    ]
