# Generated by Django 5.1.3 on 2024-11-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_check', '0002_worker_ascendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='ascendant',
            field=models.IntegerField(verbose_name='асцендент'),
        ),
    ]
